version: '3.1'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: app_user
      MONGO_INITDB_ROOT_PASSWORD: app_password
      MONGO_INITDB_DATABASE: poc-sentry-db
    volumes:
      - ./users.js:/docker-entrypoint-initdb.d/users.js:ro
      - ~/volumes/sentry/mongo-data:/data/db
      - ~/volumes/sentry/mongodb_config:/data/configdb