version: '3.1'
services:
  postgree-db:
    image: 'postgres:13.1'
    container_name: poc-sentry-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_sentry-poc
    volumes:
      - ~/volumes/sentry/postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db_sentry-poc
    volumes:
      - ~/volumes/sentry/mongo-data:/data/db
